'use client'
import { useEffect,useState } from 'react'
import { api,money } from '../../lib/api'
import { useI18n } from '../../lib/i18n'
import DateRange from '../../components/DateRange'
import StatCard from '../../components/StatCard'
function qs(period){const p=new URLSearchParams();p.set('range',period.range||'today');if(period.from_date)p.set('from_date',period.from_date);if(period.to_date)p.set('to_date',period.to_date);return p.toString()}
export default function Dashboard(){const{t}=useI18n();const[period,setPeriod]=useState({range:'today'}),[overview,setOverview]=useState(null),[products,setProducts]=useState([]),[agents,setAgents]=useState([]),[error,setError]=useState('');useEffect(()=>{const q=qs(period);Promise.all([api(`/analytics/overview?${q}`),api(`/analytics/products?${q}`),api(`/analytics/agents?${q}`)]).then(([o,p,a])=>{setOverview(o);setProducts(p);setAgents(a);setError('')}).catch(e=>setError(e.message))},[period]);return <><div className="page-head"><div><h1>{t('Dashboard')}</h1><p>{t('COD operations by date, product and agent.')}</p></div><DateRange value={period} onChange={setPeriod}/></div>{error&&<div className="error">{error}</div>}{overview&&<div className="stats-grid"><StatCard label={t('Leads')} value={overview.leads} tone="brand"/><StatCard label={t('Called')} value={overview.called}/><StatCard label={t('Confirmed')} value={overview.confirmed} note={`${overview.confirmation_rate}% ${t('CR')}`} tone="success"/><StatCard label={t('Delivered')} value={overview.delivered} note={`${overview.confirmed_to_delivered_rate}% ${t('of confirmed')}`} tone="success"/><StatCard label={t('No Answer')} value={overview.no_answer} tone="warning"/><StatCard label={t('Callbacks')} value={overview.callbacks} tone="warning"/><StatCard label={t('Confirmed Revenue')} value={money(overview.confirmed_revenue)} tone="brand"/><StatCard label={t('Agent Payout Due')} value={money(overview.agent_payout_due)} tone="warning"/></div>}
<div className="panel"><div className="panel-head"><h2>{t('Product performance')}</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>{t('Product')}</th><th>{t('Leads')}</th><th>{t('Called')}</th><th>{t('Confirmed')}</th><th>{t('CR')}</th><th>{t('Delivered')}</th><th>{t('Delivery %')}</th><th>{t('Revenue')}</th></tr></thead><tbody>{products.map(p=><tr key={p.product_id}><td><strong>{p.name}</strong><br/><small>{p.sku}</small></td><td>{p.leads}</td><td>{p.called}</td><td>{p.confirmed}</td><td>{p.confirmation_rate}%</td><td>{p.delivered}</td><td>{p.delivery_rate}%</td><td>{money(p.delivered_revenue)}</td></tr>)}</tbody></table></div></div>
<div className="panel"><div className="panel-head"><h2>{t('Agent performance')}</h2></div><div className="table-wrap"><table className="table"><thead><tr><th>{t('Agent')}</th><th>{t('Assigned')}</th><th>{t('Called')}</th><th>{t('Confirmed')}</th><th>{t('CR')}</th><th>{t('Delivered')}</th><th>{t('Delivery %')}</th><th>{t('Due')}</th></tr></thead><tbody>{agents.map(a=><tr key={a.agent_id}><td><strong>{a.display_name}</strong></td><td>{a.assigned}</td><td>{a.called}</td><td>{a.confirmed}</td><td>{a.confirmation_rate}%</td><td>{a.delivered}</td><td>{a.delivery_rate}%</td><td>{money(a.unpaid_balance)}</td></tr>)}</tbody></table></div></div></>}
